
name: Deploy Docs
env:
  FLUTTER_VERSION: "3.27.2"
on:
  push:
    branches:
      # make sure this is the branch you are using
      - develop

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
#          channel: stable
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
      - name: Install Example
        working-directory: example
        run: |-
          flutter pub get
          flutter build web --base-href "/triones-antd-mobile-flutter/web/"
          cp -r build/web/* ../website/public/web

      - name: Install pnpm
        working-directory: website
        run: npm install -g pnpm

      - name: Install Deps
        run: pnpm --dir website  install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm --dir website run docs:build
         

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: ./website/.vitepress/dist
